import { useState, useEffect, useMemo } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { adminApi } from '../../services/api';
import { useSchoolReady } from '@/hooks/useSchoolReady';
import { PASSWORD_POLICY_HINT, validatePasswordStrength } from '@/lib/passwordPolicy';
import Modal from '../ui/Modal';
import Button from '../ui/Button';
import EnrollmentTuitionSummary from './EnrollmentTuitionSummary';
import { getCurrentAcademicYear } from '@/utils/academicYear';
import toast from 'react-hot-toast';
import { 
  FiUser, 
  FiMail, 
  FiLock, 
  FiCalendar, 
  FiMapPin, 
  FiPhone, 
  FiUserCheck, 
  FiAlertCircle,
  FiBook,
  FiCheck,
  FiSave,
  FiLoader
} from 'react-icons/fi';

interface AddStudentModalProps {
  isOpen: boolean;
  onClose: () => void;
}

function formatApiError(error: unknown, fallback: string): string {
  const data = (error as { response?: { data?: { error?: string; errors?: { param?: string; msg?: string }[] } } })
    ?.response?.data;
  if (data?.error) return data.error;
  if (Array.isArray(data?.errors) && data.errors.length > 0) {
    return data.errors
      .map((e) => (e.param ? `${e.param}: ${e.msg}` : e.msg))
      .filter(Boolean)
      .join(' · ');
  }
  return fallback;
}

type ClassOption = {
  id: string;
  name: string;
  level?: string | null;
  section?: string | null;
  academicYear?: string | null;
};

function formatLevelOption(cls: ClassOption): string {
  const level = cls.level?.trim() || cls.name;
  const name = cls.name?.trim();
  const sameNameAndLevel = name.toLowerCase() === level.toLowerCase();
  const section = cls.section?.trim();

  if (section) return `${level} sect. ${section}`;
  if (!sameNameAndLevel && name) return `${level} — ${name}`;
  return level;
}

const AddStudentModal: React.FC<AddStudentModalProps> = ({ isOpen, onClose }) => {
  const queryClient = useQueryClient();
  const schoolReady = useSchoolReady();
  const [currentStep, setCurrentStep] = useState(1);
  const [errors, setErrors] = useState<Record<string, string>>({});
  
  // Form data
  const [formData, setFormData] = useState({
    // Informations personnelles
    firstName: '',
    lastName: '',
    email: '',
    password: '',
    confirmPassword: '',
    phone: '',
    dateOfBirth: '',
    birthPlace: '',
    isRepeating: false,
    gender: 'MALE' as 'MALE' | 'FEMALE' | 'OTHER',
    
    // Informations académiques
    studentId: '',
    classId: '',
    classGroupId: '',
    enrollmentStatus: 'ACTIVE' as 'ACTIVE' | 'SUSPENDED' | 'GRADUATED',
    stateAssignment: 'NOT_STATE_ASSIGNED' as 'STATE_ASSIGNED' | 'NOT_STATE_ASSIGNED',
    enrollmentDate: new Date().toISOString().split('T')[0],
    
    // Informations de contact
    address: '',
    emergencyContact: '',
    emergencyPhone: '',
    emergencyContact2: '',
    emergencyPhone2: '',
    medicalInfo: '',
    allergies: '',
    specialNeeds: '',
  });

  // Fetch classes
  const { data: classes } = useQuery({
    queryKey: ['classes'],
    queryFn: adminApi.getClasses,
    enabled: isOpen && schoolReady,
  });

  const classOptions = classes as ClassOption[] | undefined;

  const selectedClass = useMemo(
    () => classOptions?.find((c) => c.id === formData.classId),
    [classOptions, formData.classId]
  );

  const tuitionAcademicYear =
    selectedClass?.academicYear?.trim() || getCurrentAcademicYear();

  // Track if studentId was auto-generated (to prevent re-generation)
  const [studentIdAutoGenerated, setStudentIdAutoGenerated] = useState(false);

  // Generate student ID automatically only once when firstName and lastName are first entered
  useEffect(() => {
    // Only generate if studentId is empty, names are filled, and we haven't auto-generated yet
    if (!formData.studentId && formData.firstName && formData.lastName && !studentIdAutoGenerated) {
      const initials = `${formData.firstName[0]?.toUpperCase() || ''}${formData.lastName[0]?.toUpperCase() || ''}`;
      const random = Math.floor(Math.random() * 10000).toString().padStart(4, '0');
      setFormData(prev => ({
        ...prev,
        studentId: `STU${initials}${random}`,
      }));
      setStudentIdAutoGenerated(true);
    }
  }, [formData.firstName, formData.lastName, studentIdAutoGenerated]);

  // Mutation pour créer l'élève
  const createStudentMutation = useMutation({
    mutationFn: adminApi.createStudent,
    onSuccess: (data: unknown) => {
      queryClient.invalidateQueries({ queryKey: ['students'] });
      queryClient.invalidateQueries({ queryKey: ['admin-dashboard'] });
      const sent = (data as { passwordSetupEmailSent?: boolean })?.passwordSetupEmailSent;
      toast.success(
        sent
          ? 'Élève créé. Un lien pour choisir le mot de passe a été envoyé à son e-mail (valide 48 h).'
          : 'Élève créé avec succès !'
      );
      handleClose();
    },
    onError: (error: unknown) => {
      const errorMessage = formatApiError(error, "Erreur lors de la création de l'élève");
      toast.error(errorMessage);
      const validationList = (error as { response?: { data?: { errors?: { param?: string; msg?: string }[] } } })
        ?.response?.data?.errors;
      if (validationList) {
        const validationErrors: Record<string, string> = {};
        validationList.forEach((err) => {
          if (err.param) validationErrors[err.param] = err.msg ?? '';
        });
        setErrors(validationErrors);
      }
    },
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    const { name, value } = e.target;
    if (name === 'classId') {
      setFormData((prev) => ({ ...prev, classId: value, classGroupId: '' }));
    } else {
      setFormData((prev) => ({ ...prev, [name]: value }));
    }
    // Clear error when user starts typing
    if (errors[name]) {
      setErrors(prev => {
        const newErrors = { ...prev };
        delete newErrors[name];
        return newErrors;
      });
    }
  };

  const validateStep = (step: number): boolean => {
    const newErrors: Record<string, string> = {};

    if (step === 1) {
      if (!formData.firstName.trim()) newErrors.firstName = 'Le prénom est requis';
      if (!formData.lastName.trim()) newErrors.lastName = 'Le nom est requis';
      if (!formData.email.trim()) {
        newErrors.email = 'L\'email est requis';
      } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
        newErrors.email = 'Email invalide';
      }
      const pw = formData.password.trim();
      const cpw = formData.confirmPassword.trim();
      if (pw.length > 0) {
        const policyError = validatePasswordStrength(pw);
        if (policyError) newErrors.password = policyError;
        if (pw !== cpw) {
          newErrors.confirmPassword = 'Les mots de passe ne correspondent pas';
        }
      } else if (cpw.length > 0) {
        newErrors.confirmPassword = 'Videz la confirmation ou saisissez un mot de passe';
      }
      if (!formData.dateOfBirth) newErrors.dateOfBirth = 'La date de naissance est requise';
      if (!formData.gender) newErrors.gender = 'Le genre est requis';
    }

    if (step === 2) {
      if (!formData.studentId.trim()) newErrors.studentId = 'Le numéro d\'élève est requis';
    }

    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleNext = () => {
    if (validateStep(currentStep)) {
      setCurrentStep(prev => Math.min(prev + 1, 3));
    }
  };

  const handlePrevious = () => {
    setCurrentStep(prev => Math.max(prev - 1, 1));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!validateStep(1) || !validateStep(2) || !validateStep(3)) {
      return;
    }

    const pw = formData.password.trim();
    const submitData = {
      email: formData.email,
      ...(pw.length > 0 && !validatePasswordStrength(pw) ? { password: pw } : {}),
      firstName: formData.firstName,
      lastName: formData.lastName,
      phone: formData.phone || undefined,
      studentId: formData.studentId,
      dateOfBirth: formData.dateOfBirth,
      birthPlace: formData.birthPlace.trim() || undefined,
      isRepeating: formData.isRepeating,
      gender: formData.gender,
      address: formData.address || undefined,
      emergencyContact: formData.emergencyContact || undefined,
      emergencyPhone: formData.emergencyPhone || undefined,
      emergencyContact2: formData.emergencyContact2 || undefined,
      emergencyPhone2: formData.emergencyPhone2 || undefined,
      medicalInfo: formData.medicalInfo || undefined,
      allergies: formData.allergies || undefined,
      specialNeeds: formData.specialNeeds || undefined,
      classId: formData.classId || undefined,
      ...(formData.classGroupId ? { classGroupId: formData.classGroupId } : {}),
      enrollmentDate: formData.enrollmentDate,
      enrollmentStatus: formData.enrollmentStatus,
      stateAssignment: formData.stateAssignment,
    };

    createStudentMutation.mutate(submitData);
  };

  const handleClose = () => {
    setCurrentStep(1);
    setFormData({
      firstName: '',
      lastName: '',
      email: '',
      password: '',
      confirmPassword: '',
      phone: '',
      dateOfBirth: '',
      birthPlace: '',
      isRepeating: false,
      gender: 'MALE',
      studentId: '',
      classId: '',
      classGroupId: '',
      enrollmentStatus: 'ACTIVE',
      stateAssignment: 'NOT_STATE_ASSIGNED',
      enrollmentDate: new Date().toISOString().split('T')[0],
      address: '',
      emergencyContact: '',
      emergencyPhone: '',
      emergencyContact2: '',
      emergencyPhone2: '',
      medicalInfo: '',
      allergies: '',
      specialNeeds: '',
    });
    setStudentIdAutoGenerated(false);
    setErrors({});
    onClose();
  };

  const steps = [
    { number: 1, title: 'Informations Personnelles', icon: FiUser },
    { number: 2, title: 'Informations Académiques', icon: FiBook },
    { number: 3, title: 'Contact & Santé', icon: FiPhone },
  ];

  return (
    <Modal isOpen={isOpen} onClose={handleClose} title="Ajouter un Élève" size="lg" compact>
      <div className="space-y-2">
        {/* Progress Steps */}
        <div className="flex items-center justify-between mb-2">
          {steps.map((step, index) => {
            const StepIcon = step.icon;
            const isActive = currentStep === step.number;
            const isCompleted = currentStep > step.number;
            
            return (
              <div key={step.number} className="flex items-center flex-1">
                <div className="flex flex-col items-center flex-1">
                  <div
                    className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-[10px] transition-all duration-300 ${
                      isActive
                        ? 'bg-gradient-to-br from-stone-900 via-amber-900 to-stone-950 text-amber-50 ring-1 ring-amber-400/35 shadow-lg'
                        : isCompleted
                        ? 'bg-gradient-to-br from-emerald-800 to-teal-900 text-emerald-50 ring-1 ring-emerald-400/25'
                        : 'bg-stone-200 text-stone-500'
                    }`}
                  >
                    {isCompleted ? (
                      <FiCheck className="w-4 h-4" />
                    ) : (
                      <StepIcon className="w-4 h-4" />
                    )}
                  </div>
                  <p className={`mt-1 text-[10px] font-medium text-center leading-tight px-0.5 ${
                    isActive ? 'text-amber-800' : isCompleted ? 'text-emerald-800' : 'text-stone-500'
                  }`}>
                    {step.title}
                  </p>
                </div>
                {index < steps.length - 1 && (
                  <div className={`flex-1 h-0.5 mx-1 transition-all duration-300 ${
                    isCompleted ? 'bg-gradient-to-r from-emerald-700 to-teal-700' : 'bg-stone-200'
                  }`} />
                )}
              </div>
            );
          })}
        </div>

        <form onSubmit={handleSubmit} className="space-y-2">
          {/* Step 1: Informations Personnelles */}
          {currentStep === 1 && (
            <div className="space-y-2 animate-fade-in">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Prénom <span className="text-red-500">*</span>
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                      <FiUser className="h-3.5 w-3.5 text-stone-400" />
                    </div>
                    <input
                      type="text"
                      name="firstName"
                      value={formData.firstName}
                      onChange={handleChange}
                      className={`w-full pl-8 pr-3 py-1.5 text-sm border rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all ${
                        errors.firstName ? 'border-red-500' : 'border-stone-200'
                      }`}
                      placeholder="Prénom"
                    />
                  </div>
                  {errors.firstName && (
                    <p className="mt-1 text-xs text-red-500 flex items-center">
                      <FiAlertCircle className="w-3.5 h-3.5 mr-1 shrink-0" />
                      {errors.firstName}
                    </p>
                  )}
                </div>

                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Nom <span className="text-red-500">*</span>
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                      <FiUser className="h-3.5 w-3.5 text-stone-400" />
                    </div>
                    <input
                      type="text"
                      name="lastName"
                      value={formData.lastName}
                      onChange={handleChange}
                      className={`w-full pl-8 pr-3 py-1.5 text-sm border rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all ${
                        errors.lastName ? 'border-red-500' : 'border-stone-200'
                      }`}
                      placeholder="Nom"
                    />
                  </div>
                  {errors.lastName && (
                    <p className="mt-1 text-xs text-red-500 flex items-center">
                      <FiAlertCircle className="w-3.5 h-3.5 mr-1 shrink-0" />
                      {errors.lastName}
                    </p>
                  )}
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">
                  Email <span className="text-red-500">*</span>
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                    <FiMail className="h-3.5 w-3.5 text-stone-400" />
                  </div>
                  <input
                    type="email"
                    name="email"
                    value={formData.email}
                    onChange={handleChange}
                    className={`w-full pl-8 pr-3 py-1.5 text-sm border rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all ${
                      errors.email ? 'border-red-500' : 'border-stone-200'
                    }`}
                    placeholder="email@exemple.com"
                  />
                </div>
                {errors.email && (
                  <p className="mt-1 text-xs text-red-500 flex items-center">
                    <FiAlertCircle className="w-3.5 h-3.5 mr-1 shrink-0" />
                    {errors.email}
                  </p>
                )}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Mot de passe <span className="text-stone-500 font-normal">(optionnel)</span>
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                      <FiLock className="h-3.5 w-3.5 text-stone-400" />
                    </div>
                    <input
                      type="password"
                      name="password"
                      value={formData.password}
                      onChange={handleChange}
                      className={`w-full pl-8 pr-3 py-1.5 text-sm border rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all ${
                        errors.password ? 'border-red-500' : 'border-stone-200'
                      }`}
                      placeholder="Laisser vide = lien par e-mail"
                      autoComplete="new-password"
                    />
                  </div>
                  <p className="mt-0.5 text-[11px] text-stone-500 leading-snug">
                    Si vide, l’élève reçoit un e-mail pour définir son mot de passe (48 h). Sinon : {PASSWORD_POLICY_HINT}
                  </p>
                  {errors.password && (
                    <p className="mt-1 text-xs text-red-500 flex items-center">
                      <FiAlertCircle className="w-3.5 h-3.5 mr-1 shrink-0" />
                      {errors.password}
                    </p>
                  )}
                </div>

                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Confirmer le mot de passe
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                      <FiLock className="h-3.5 w-3.5 text-stone-400" />
                    </div>
                    <input
                      type="password"
                      name="confirmPassword"
                      value={formData.confirmPassword}
                      onChange={handleChange}
                      className={`w-full pl-8 pr-3 py-1.5 text-sm border rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all ${
                        errors.confirmPassword ? 'border-red-500' : 'border-stone-200'
                      }`}
                      placeholder="Même mot de passe si renseigné"
                      autoComplete="new-password"
                    />
                  </div>
                  {errors.confirmPassword && (
                    <p className="mt-1 text-xs text-red-500 flex items-center">
                      <FiAlertCircle className="w-3.5 h-3.5 mr-1 shrink-0" />
                      {errors.confirmPassword}
                    </p>
                  )}
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div>
                  <label htmlFor="add-student-date-of-birth" className="block text-xs font-semibold text-stone-700 mb-1">
                    Date de naissance <span className="text-red-500">*</span>
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                      <FiCalendar className="h-3.5 w-3.5 text-stone-400" />
                    </div>
                    <input
                      id="add-student-date-of-birth"
                      type="date"
                      name="dateOfBirth"
                      value={formData.dateOfBirth}
                      onChange={handleChange}
                      max={new Date().toISOString().split('T')[0]}
                      className={`w-full pl-8 pr-3 py-1.5 text-sm border rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all ${
                        errors.dateOfBirth ? 'border-red-500' : 'border-stone-200'
                      }`}
                    />
                  </div>
                  {errors.dateOfBirth && (
                    <p className="mt-1 text-xs text-red-500 flex items-center">
                      <FiAlertCircle className="w-3.5 h-3.5 mr-1 shrink-0" />
                      {errors.dateOfBirth}
                    </p>
                  )}
                </div>

                <div>
                  <label htmlFor="add-student-birth-place" className="block text-xs font-semibold text-stone-700 mb-1">
                    Lieu de naissance
                  </label>
                  <input
                    id="add-student-birth-place"
                    type="text"
                    name="birthPlace"
                    value={formData.birthPlace}
                    onChange={handleChange}
                    placeholder="Ex. Bouaké, Abidjan…"
                    className="w-full px-3 py-1.5 text-sm border border-stone-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                  />
                </div>

                <div>
                  <label htmlFor="add-student-gender" className="block text-xs font-semibold text-stone-700 mb-1">
                    Genre <span className="text-red-500">*</span>
                  </label>
                  <select
                    id="add-student-gender"
                    name="gender"
                    value={formData.gender}
                    onChange={handleChange}
                    className={`w-full px-3 py-1.5 text-sm border rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all ${
                      errors.gender ? 'border-red-500' : 'border-stone-200'
                    }`}
                  >
                    <option value="MALE">Masculin</option>
                    <option value="FEMALE">Féminin</option>
                    <option value="OTHER">Autre</option>
                  </select>
                  {errors.gender && (
                    <p className="mt-1 text-xs text-red-500 flex items-center">
                      <FiAlertCircle className="w-3.5 h-3.5 mr-1 shrink-0" />
                      {errors.gender}
                    </p>
                  )}
                </div>

                <div>
                  <label htmlFor="add-student-is-repeating" className="block text-xs font-semibold text-stone-700 mb-1">
                    Doublant (e)
                  </label>
                  <select
                    id="add-student-is-repeating"
                    name="isRepeating"
                    value={formData.isRepeating ? 'true' : 'false'}
                    onChange={(e) =>
                      setFormData((prev) => ({ ...prev, isRepeating: e.target.value === 'true' }))
                    }
                    className="w-full px-3 py-1.5 text-sm border border-stone-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                  >
                    <option value="false">Non</option>
                    <option value="true">Oui</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">
                  Téléphone
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                    <FiPhone className="h-3.5 w-3.5 text-stone-400" />
                  </div>
                  <input
                    type="tel"
                    name="phone"
                    value={formData.phone}
                    onChange={handleChange}
                    className="w-full pl-8 pr-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                    placeholder="+33 6 12 34 56 78"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Step 2: Informations Académiques */}
          {currentStep === 2 && (
            <div className="space-y-2 animate-fade-in">
              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">
                  Numéro d'élève <span className="text-red-500">*</span>
                </label>
                <div className="relative">
                  <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                    <FiBook className="h-3.5 w-3.5 text-stone-400" />
                  </div>
                  <input
                    type="text"
                    name="studentId"
                    value={formData.studentId}
                    onChange={handleChange}
                    className={`w-full pl-8 pr-3 py-1.5 text-sm border rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all ${
                      errors.studentId ? 'border-red-500' : 'border-stone-200'
                    }`}
                    placeholder="STU001234"
                  />
                </div>
                <p className="mt-0.5 text-[10px] text-gray-500">Généré automatiquement si vide</p>
                {errors.studentId && (
                  <p className="mt-1 text-xs text-red-500 flex items-center">
                    <FiAlertCircle className="w-3.5 h-3.5 mr-1 shrink-0" />
                    {errors.studentId}
                  </p>
                )}
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div>
                  <label htmlFor="add-student-class-id" className="block text-xs font-semibold text-stone-700 mb-1">
                    Niveau
                  </label>
                  <select
                    id="add-student-class-id"
                    name="classId"
                    value={formData.classId}
                    onChange={handleChange}
                    className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                  >
                    <option value="">Sélectionner un niveau</option>
                    {classOptions?.map((cls) => (
                      <option key={cls.id} value={cls.id}>
                        {formatLevelOption(cls)}
                      </option>
                    ))}
                  </select>
                </div>

                {formData.classId ? (
                  <div className="md:col-span-2">
                    <EnrollmentTuitionSummary
                      classId={formData.classId}
                      academicYear={tuitionAcademicYear}
                      classLabel={
                        selectedClass
                          ? formatLevelOption(selectedClass)
                          : undefined
                      }
                    />
                  </div>
                ) : null}

                <div>
                  <label htmlFor="add-student-class-group-id" className="block text-xs font-semibold text-stone-700 mb-1">
                    Groupe <span className="text-stone-400 font-normal">(optionnel)</span>
                  </label>
                  <select
                    id="add-student-class-group-id"
                    name="classGroupId"
                    value={formData.classGroupId}
                    onChange={handleChange}
                    disabled={!formData.classId}
                    className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all disabled:opacity-50"
                  >
                    <option value="">Aucun groupe</option>
                    {(classes?.find((c: any) => c.id === formData.classId)?.groups || [])
                      .slice()
                      .sort((a: any, b: any) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0))
                      .map((g: any) => (
                        <option key={g.id} value={g.id}>
                          {g.name}
                        </option>
                      ))}
                  </select>
                </div>

                <div>
                  <label htmlFor="add-student-enrollment-date" className="block text-xs font-semibold text-stone-700 mb-1">
                    Date d'inscription
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                      <FiCalendar className="h-3.5 w-3.5 text-stone-400" />
                    </div>
                    <input
                      id="add-student-enrollment-date"
                      type="date"
                      name="enrollmentDate"
                      value={formData.enrollmentDate}
                      onChange={handleChange}
                      className="w-full pl-8 pr-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                    />
                  </div>
                </div>
              </div>

              <div>
                <label htmlFor="add-enrollmentStatus" className="block text-xs font-semibold text-stone-700 mb-1">
                  Statut d&apos;inscription
                </label>
                <select
                  id="add-enrollmentStatus"
                  name="enrollmentStatus"
                  value={formData.enrollmentStatus}
                  onChange={handleChange}
                  className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                >
                  <option value="ACTIVE">Inscription active</option>
                  <option value="SUSPENDED">Inscription suspendue</option>
                  <option value="GRADUATED">Diplômé·e</option>
                </select>
              </div>

              <div>
                <label htmlFor="add-stateAssignment" className="block text-xs font-semibold text-stone-700 mb-1">
                  Affectation État
                </label>
                <select
                  id="add-stateAssignment"
                  name="stateAssignment"
                  value={formData.stateAssignment}
                  onChange={handleChange}
                  className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                >
                  <option value="STATE_ASSIGNED">Affecté de l&apos;État</option>
                  <option value="NOT_STATE_ASSIGNED">Non affecté</option>
                </select>
                <p className="mt-0.5 text-[10px] text-gray-500">
                  Catégorie administrative (place / affectation au titre de l&apos;État).
                </p>
              </div>
            </div>
          )}

          {/* Step 3: Contact & Santé */}
          {currentStep === 3 && (
            <div className="space-y-2 animate-fade-in">
              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">
                  Adresse
                </label>
                <div className="relative">
                  <div className="absolute top-2 left-2.5 flex items-start pointer-events-none">
                    <FiMapPin className="h-3.5 w-3.5 text-stone-400" />
                  </div>
                  <textarea
                    name="address"
                    value={formData.address}
                    onChange={handleChange}
                    rows={2}
                    className="w-full pl-8 pr-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all resize-none"
                    placeholder="Adresse complète"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Contact d'urgence
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                      <FiUserCheck className="h-3.5 w-3.5 text-stone-400" />
                    </div>
                    <input
                      type="text"
                      name="emergencyContact"
                      value={formData.emergencyContact}
                      onChange={handleChange}
                      className="w-full pl-8 pr-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                      placeholder="Nom du contact"
                    />
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Téléphone d'urgence
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-2.5 flex items-center pointer-events-none">
                      <FiPhone className="h-3.5 w-3.5 text-stone-400" />
                    </div>
                    <input
                      type="tel"
                      name="emergencyPhone"
                      value={formData.emergencyPhone}
                      onChange={handleChange}
                      className="w-full pl-8 pr-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all"
                      placeholder="+33 6 12 34 56 78"
                    />
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Second contact d&apos;urgence
                  </label>
                  <input
                    type="text"
                    name="emergencyContact2"
                    value={formData.emergencyContact2}
                    onChange={handleChange}
                    className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg"
                    placeholder="Nom"
                    aria-label="Second contact d'urgence"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Téléphone (2e contact)
                  </label>
                  <input
                    type="tel"
                    name="emergencyPhone2"
                    value={formData.emergencyPhone2}
                    onChange={handleChange}
                    className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg"
                    placeholder="+33…"
                    aria-label="Téléphone second contact d'urgence"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">Allergies</label>
                  <textarea
                    name="allergies"
                    value={formData.allergies}
                    onChange={handleChange}
                    rows={2}
                    className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg resize-none"
                    placeholder="Facultatif"
                    aria-label="Allergies"
                  />
                </div>
                <div>
                  <label className="block text-xs font-semibold text-stone-700 mb-1">
                    Conditions particulières
                  </label>
                  <textarea
                    name="specialNeeds"
                    value={formData.specialNeeds}
                    onChange={handleChange}
                    rows={2}
                    className="w-full px-3 py-1.5 text-sm border border-gray-200 rounded-lg resize-none"
                    placeholder="Facultatif"
                    aria-label="Conditions particulières"
                  />
                </div>
              </div>

              <div>
                <label className="block text-xs font-semibold text-stone-700 mb-1">
                  Informations médicales (dossier)
                </label>
                <div className="relative">
                  <div className="absolute top-2 left-2.5 flex items-start pointer-events-none">
                    <FiAlertCircle className="h-3.5 w-3.5 text-stone-400" />
                  </div>
                  <textarea
                    name="medicalInfo"
                    value={formData.medicalInfo}
                    onChange={handleChange}
                    rows={3}
                    className="w-full pl-8 pr-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-amber-500/25 focus:border-amber-500/40 transition-all resize-none"
                    placeholder="Suivi, traitements, consignes…"
                  />
                </div>
              </div>
            </div>
          )}

          {/* Navigation Buttons */}
          <div className="flex items-center justify-between pt-3 border-t border-gray-200">
            <div>
              {currentStep > 1 && (
                <Button
                  type="button"
                  variant="secondary"
                  size="sm"
                  onClick={handlePrevious}
                  disabled={createStudentMutation.isPending}
                >
                  Précédent
                </Button>
              )}
            </div>
            <div className="flex items-center gap-2">
              <Button
                type="button"
                variant="secondary"
                size="sm"
                onClick={handleClose}
                disabled={createStudentMutation.isPending}
              >
                Annuler
              </Button>
              {currentStep < 3 ? (
                <Button type="button" size="sm" onClick={handleNext} disabled={createStudentMutation.isPending}>
                  Suivant
                </Button>
              ) : (
                <Button
                  type="submit"
                  size="sm"
                  disabled={createStudentMutation.isPending}
                  className="min-w-[120px]"
                >
                  {createStudentMutation.isPending ? (
                    <>
                      <FiLoader className="w-4 h-4 mr-1.5 animate-spin inline" />
                      Création...
                    </>
                  ) : (
                    <>
                      <FiSave className="w-4 h-4 mr-1.5 inline" />
                      Créer l'élève
                    </>
                  )}
                </Button>
              )}
            </div>
          </div>
        </form>
      </div>
    </Modal>
  );
};

export default AddStudentModal;

